// project api
[
    {
      "projectrequestid": "177",
      "projectrefid": "PR-615D",
      "planned": "Dec 26 - Mar 05",
      "pstartdate": "2021-12-25T20:00:00.000Z",
      "penddate": "2022-03-04T20:00:00.000Z",
      "actual": "Dec 28 - Dec 31",
      "astartdate": "2021-12-27T20:00:00.000Z",
      "aenddate": "2021-12-30T20:00:00.000Z",
      "projectname": "Project11",
      "projectdesc": "demo",
      "budgetedamount": "989.00",
      "actualbudget": "1920.00",
      "statusid": 500,
      "statustext": "Approved",
      "statusclass": "#1FC875",
      "projectlead": "Tariq Eqbal",
      "projectleadimage": "",
      "domainlead": "Atiq Ur Rehman",
      "domainleadimage": "",
      "milestone_count": "30",
      "creater_id": "93",
      "businessunitid": 7,
      "changedenddate": "2022-01-16T20:00:00.000Z",
      "planningefforts": "0",
      "changedapprovedbudget": "10.00",
      "priority": "High",
      "scrummasterid": null,
      "businessprojectmanagerid": "Abul",
      "projectphase": "401"
    },
    {
      "projectrequestid": "178",
      "projectrefid": "PR-7289",
      "planned": "Jan 01 - Mar 11",
      "pstartdate": "2021-12-31T20:00:00.000Z",
      "penddate": "2022-03-10T20:00:00.000Z",
      "actual": "Dec 15 - Jan 27",
      "astartdate": "2021-12-14T20:00:00.000Z",
      "aenddate": "2022-01-26T20:00:00.000Z",
      "projectname": "Project 2",
      "projectdesc": "sdfsdf",
      "budgetedamount": "3780.00",
      "actualbudget": "111.00",
      "statusid": 500,
      "statustext": "Approved",
      "statusclass": "#1FC875",
      "projectlead": "Binoo Joseph.",
      "projectleadimage": "",
      "domainlead": "Ashar Ahmed Syed",
      "domainleadimage": "",
      "milestone_count": "3",
      "creater_id": "28",
      "businessunitid": 71,
      "changedenddate": "2022-01-16T20:00:00.000Z",
      "planningefforts": "0",
      "changedapprovedbudget": "1111.00",
      "priority": "Medium",
      "scrummasterid": null,
      "businessprojectmanagerid": "Shah Rashad",
      "projectphase": "401"
    },
    {
      "projectrequestid": "184",
      "projectrefid": "PR-EAE7",
      "planned": "Jan 01 - Mar 31",
      "pstartdate": "2021-12-31T20:00:00.000Z",
      "penddate": "2022-03-30T20:00:00.000Z",
      "actual": " - ",
      "astartdate": null,
      "aenddate": null,
      "projectname": "Demo Project 1",
      "projectdesc": "demo project 1 description",
      "budgetedamount": "900.00",
      "actualbudget": null,
      "statusid": 1,
      "statustext": "Approved",
      "statusclass": "#1FC875",
      "projectlead": "Rahat Ali",
      "projectleadimage": "",
      "domainlead": null,
      "domainleadimage": null,
      "milestone_count": "3",
      "creater_id": "110",
      "businessunitid": 79,
      "changedenddate": null,
      "planningefforts": null,
      "changedapprovedbudget": null,
      "priority": null,
      "scrummasterid": null,
      "businessprojectmanagerid": "Kannan Parthasarathy",
      "projectphase": null
    },
    {
      "projectrequestid": "187",
      "projectrefid": "PR-2391",
      "planned": "Jan 17 - Apr 30",
      "pstartdate": "2022-01-16T20:00:00.000Z",
      "penddate": "2022-04-29T20:00:00.000Z",
      "actual": " - ",
      "astartdate": null,
      "aenddate": null,
      "projectname": "demo 2",
      "projectdesc": "demo",
      "budgetedamount": "454000.00",
      "actualbudget": null,
      "statusid": 1,
      "statustext": "Approved",
      "statusclass": "#1FC875",
      "projectlead": "Revathi Ananda",
      "projectleadimage": "",
      "domainlead": "Revathi Ananda",
      "domainleadimage": "",
      "milestone_count": "0",
      "creater_id": "26",
      "businessunitid": 11,
      "changedenddate": null,
      "planningefforts": null,
      "changedapprovedbudget": null,
      "priority": null,
      "scrummasterid": null,
      "businessprojectmanagerid": "Ashar Ahmed Syed",
      "projectphase": null
    }
]

//milestone api
[
    {
      "taskid": "112",
      "projectid": "178",
      "taskname": "asdasdasd",
      "taskdesc": "asdasdasd",
      "ownerid": "25",
      "ownername": "Ashar Ahmed Syed",
      "ownerimage": "",
      "statusid": 205,
      "statustext": "At Risk",
      "statusclass": "#E2445B",
      "planned": "Dec 30 - Dec 30",
      "actual": " - ",
      "pstartdate": "2021-12-29T20:00:00.000Z",
      "penddate": "2021-12-29T20:00:00.000Z",
      "tasks_count": "0",
      "createdby": "25"
    },
    {
      "taskid": "145",
      "projectid": "178",
      "taskname": "demo",
      "taskdesc": "demo",
      "ownerid": "25",
      "ownername": "Ashar Ahmed Syed",
      "ownerimage": "",
      "statusid": 21,
      "statustext": null,
      "statusclass": null,
      "planned": "Jan 07 - Jan 19",
      "actual": " - ",
      "pstartdate": "2022-01-06T20:00:00.000Z",
      "penddate": "2022-01-18T20:00:00.000Z",
      "tasks_count": "0",
      "createdby": "25"
    },
    {
      "taskid": "146",
      "projectid": "178",
      "taskname": "demo",
      "taskdesc": "asdsadsadsd",
      "ownerid": "25",
      "ownername": "Ashar Ahmed Syed",
      "ownerimage": "",
      "statusid": 21,
      "statustext": null,
      "statusclass": null,
      "planned": "Jan 06 - Jan 12",
      "actual": " - ",
      "pstartdate": "2022-01-05T20:00:00.000Z",
      "penddate": "2022-01-11T20:00:00.000Z",
      "tasks_count": "0",
      "createdby": "25"
    }
]


// Array Format

const projectData=
[
  {
    projectrequestid: "177",
    projectrefid: "PR-615D",
    planned: "Jan 03 - Mar 06",
    startExactDay: '03 Jan 2021',
    startMonth: '2021/01/01',
    duration: '15 days',
    percentage: '80%',
    pstartdate: "2021/01/03T20:00:00.000Z",
    penddate: "2023/03/06T20:00:00.000Z",
    actual: "Dec 28 - Dec 31",
    astartdate: "2021-12-27T20:00:00.000Z",
    aenddate: "2021-12-30T20:00:00.000Z",
    projectname: "Project 1 Project 1 Project 1 Project 1 Project 1",
    projectdesc: "demo",
    budgetedamount: "989.00",
    actualbudget: "1920.00",
    statusid: 500,
    statustext: "Approved",
    statusclass: "#1FC875",
    projectlead: "Tariq Eqbal",
    projectleadimage: "",
    domainlead: "Atiq Ur Rehman",
    technicallead: null,
    programmanager:null,
    domainleadimage: "",
    milestone_count: "30",
    creater_id: "93",
    businessunitid: 7,
    changedenddate: "2022-01-16T20:00:00.000Z",
    planningefforts: "0",
    changedapprovedbudget: "10.00",
    priority: "High",
    scrummasterid: null,
    businessprojectmanagerid: "Abul",
    projectphase: "401"
  },
  {
    projectrequestid: "177",
    projectrefid: "PR-615D",
    planned: "Apr 02 - Apr 30",
    startExactDay: '02 Apr 2021',
    startMonth: '2021/04/01',
    duration: '15 days',
    percentage: '80%',
    pstartdate: "2021/04/02T20:00:00.000Z",
    penddate: "2021/04/30T20:00:00.000Z",
    actual: "Dec 28 - Dec 31",
    astartdate: "2021-12-27T20:00:00.000Z",
    aenddate: "2021-12-30T20:00:00.000Z",
    projectname: "Project 2",
    projectdesc: "demo",
    budgetedamount: "989.00",
    actualbudget: "1920.00",
    statusid: 500,
    statustext: "Approved",
    statusclass: "#1FC875",
    projectlead: "Tariq Eqbal",
    projectleadimage: "",
    domainlead: "Atiq Ur Rehman",
    technicallead: null,
    programmanager:null,
    domainleadimage: "",
    milestone_count: "30",
    creater_id: "93",
    businessunitid: 7,
    changedenddate: "2022-01-16T20:00:00.000Z",
    planningefforts: "0",
    changedapprovedbudget: "10.00",
    priority: "High",
    scrummasterid: null,
    businessprojectmanagerid: "Abul",
    projectphase: "401"
  }
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Mar 01 - Aug 25",
  //   startExactDay: '01 Mar 2022',
  //   startMonth: '2022/03/01',
  //   duration: '178 days',
  //   percentage: '90%',
  //   pstartdate: "2022-03-01T20:00:00.000Z",
  //   penddate: "2022-08-25T20:00:00.000Z",
  //   actual: "Dec 15 - Jan 27",
  //   astartdate: "2021-12-14T20:00:00.000Z",
  //   aenddate: "2022-01-26T20:00:00.000Z",
  //   projectname: "Project 2",
  //   projectdesc: "sdfsdf",
  //   budgetedamount: "3780.00",
  //   actualbudget: "111.00",
  //   statusid: 500,
  //   statustext: "Approved",
  //   statusclass: "#1FC875",
  //   projectlead: "Binoo Joseph.",
  //   projectleadimage: "",
  //   domainlead: "Ashar Ahmed Syed",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "3",
  //   creater_id: "28",
  //   businessunitid: 71,
  //   changedenddate: "2022-01-16T20:00:00.000Z",
  //   planningefforts: "0",
  //   changedapprovedbudget: "1111.00",
  //   priority: "Medium",
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Shah Rashad",
  //   projectphase: "401"
  // },
  // {
  //   projectrequestid: "184",
  //   projectrefid: "PR-EAE7",
  //   planned: "Jan 01 - Jun 14",
  //   startExactDay: '01 Jan 2022',
  //   startMonth: '2022/01/01',
  //   duration: '165 days',
  //   percentage: '70%',
  //   pstartdate: "2022-01-01T20:00:00.000Z",
  //   penddate: "2022-06-14T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 3",
  //   projectdesc: "demo project 1 description",
  //   budgetedamount: "900.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "Approved",
  //   statusclass: "#1FC875",
  //   projectlead: "Rahat Ali",
  //   projectleadimage: "",
  //   domainlead: null,
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: null,
  //   milestone_count: "3",
  //   creater_id: "110",
  //   businessunitid: 79,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Kannan Parthasarathy",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Jan 17 - Apr 30",
  //   startExactDay: '17 Jan 2022',
  //   startMonth: '2022/01/01',
  //   duration: '104 days',
  //   percentage: '50%',
  //   pstartdate: "2022-01-16T20:00:00.000Z",
  //   penddate: "2022-04-29T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 4",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "Approved",
  //   statusclass: "#1FC875",
  //   projectlead: "Revathi Ananda",
  //   projectleadimage: "",
  //   domainlead: "Revathi Ananda",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Jan 03 - Jan 22",
  //   startExactDay: '03 Jan 2022',
  //   startMonth: '2022/01/01',
  //   duration: '20 days',
  //   percentage: '90%',
  //   pstartdate: "2022-01-03T20:00:00.000Z",
  //   penddate: "2022-01-22T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 5",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "Approved",
  //   statusclass: "#2762ed",
  //   projectlead: "Revathi Ananda",
  //   projectleadimage: "",
  //   domainlead: "Revathi Ananda",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Feb 01 - May 18",
  //   startExactDay: '01 Feb 2022',
  //   startMonth: '2022/02/01',
  //   duration: '107 days',
  //   percentage: '90%',
  //   pstartdate: "2022-02-01T20:00:00.000Z",
  //   penddate: "2022-05-18T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 6",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "Approved",
  //   statusclass: "#CC0078",
  //   projectlead: "Revathi Ananda",
  //   projectleadimage: "",
  //   domainlead: "Revathi Ananda",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Jan 01 - Mar 24",
  //   startExactDay: '01 Jan 2022',
  //   startMonth: '2022/01/01',
  //   duration: '82 days',
  //   percentage: '70%',
  //   pstartdate: "2022-01-01T20:00:00.000Z",
  //   penddate: "2022-03-23T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 7",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "On Hold",
  //   statusclass: "#0D5F07",
  //   projectlead: "Revathi Ananda",
  //   projectleadimage: "",
  //   domainlead: "Revathi Ananda",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Sep 03 - Dec 24",
  //   startExactDay: '03 Sep 2022',
  //   startMonth: '2022/09/01',
  //   duration: '113 days',
  //   percentage: '70%',
  //   pstartdate: "2022-09-03T20:00:00.000Z",
  //   penddate: "2022-12-24T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 8",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "On Hold",
  //   statusclass: "#F9C784",
  //   projectlead: "Revathi Ananda",
  //   projectleadimage: "",
  //   domainlead: "Revathi Ananda",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "May 03 - Jun 24",
  //   startExactDay: '03 May 2022',
  //   startMonth: '2022/05/01',
  //   duration: '53 days',
  //   percentage: '70%',
  //   pstartdate: "2022-05-03T20:00:00.000Z",
  //   penddate: "2022-06-24T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 9",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "On Hold",
  //   statusclass: "#2762ed",
  //   projectlead: "Revathi Ananda",
  //   projectleadimage: "",
  //   domainlead: "Revathi Ananda",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Feb 03 - Jun 24",
  //   startExactDay: '03 Feb 2023',
  //   startMonth: '2023/02/03',
  //   duration: '142 days',
  //   percentage: '70%',
  //   pstartdate: "2023-02-03T20:00:00.000Z",
  //   penddate: "2023-06-24T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 10",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "On Hold",
  //   statusclass: "#2762ed",
  //   projectlead: "Revathi Ananda",
  //   projectleadimage: "",
  //   domainlead: "Revathi Ananda",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Aug 23 - Oct 24",
  //   startExactDay: '23 Aug 2024',
  //   startMonth: '2024/08/03',
  //   duration: '142 days',
  //   percentage: '40%',
  //   pstartdate: "2024-08-23T20:00:00.000Z",
  //   penddate: "2024-10-24T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 11",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "Medium",
  //   statusclass: "#9D73FA",
  //   projectlead: "John",
  //   projectleadimage: "",
  //   domainlead: "Alex",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // },
  // {
  //   projectrequestid: "187",
  //   projectrefid: "PR-2391",
  //   planned: "Mar 25 - Oct 24",
  //   startExactDay: '25 Mar 2025',
  //   startMonth: '2025/03/01',
  //   duration: '142 days',
  //   percentage: '60%',
  //   pstartdate: "2025-03-25T20:00:00.000Z",
  //   penddate: "2026-10-24T20:00:00.000Z",
  //   actual: " - ",
  //   astartdate: null,
  //   aenddate: null,
  //   projectname: "Project 12",
  //   projectdesc: "demo",
  //   budgetedamount: "454000.00",
  //   actualbudget: null,
  //   statusid: 1,
  //   statustext: "Medium",
  //   statusclass: "#9D73FA",
  //   projectlead: "John",
  //   projectleadimage: "",
  //   domainlead: "Alex",
  //   technicallead: null,
  //   programmanager:null,
  //   domainleadimage: "",
  //   milestone_count: "0",
  //   creater_id: "26",
  //   businessunitid: 11,
  //   changedenddate: null,
  //   planningefforts: null,
  //   changedapprovedbudget: null,
  //   priority: null,
  //   scrummasterid: null,
  //   businessprojectmanagerid: "Ashar Ahmed Syed",
  //   projectphase: null
  // }
]

const milestoneData =
[
  {
    taskid: "112",
    projectid: "178",
    taskname: "asdasdasd",
    taskdesc: "asdasdasd",
    ownerid: "25",
    ownername: "Ashar Ahmed Syed",
    ownerimage: "",
    statusid: 205,
    statustext: "At Risk",
    statusclass: "#E2445B",
    planned: "Dec 30 - Dec 30",
    actual: " - ",
    pstartdate: "2021-12-29T20:00:00.000Z",
    penddate: "2021-12-29T20:00:00.000Z",
    tasks_count: "0",
    createdby: "25"
  },
  {
    taskid: "145",
    projectid: "178",
    taskname: "demo",
    taskdesc: "demo",
    ownerid: "25",
    ownername: "Ashar Ahmed Syed",
    ownerimage: "",
    statusid: 21,
    statustext: null,
    statusclass: null,
    planned: "Jan 07 - Jan 19",
    actual: " - ",
    pstartdate: "2022-01-06T20:00:00.000Z",
    penddate: "2022-01-18T20:00:00.000Z",
    tasks_count: "0",
    createdby: "25"
  },
  {
    taskid: "146",
    projectid: "178",
    taskname: "demo",
    taskdesc: "asdsadsadsd",
    ownerid: "25",
    ownername: "Ashar Ahmed Syed",
    ownerimage: "",
    statusid: 21,
    statustext: null,
    statusclass: null,
    planned: "Jan 06 - Jan 12",
    actual: " - ",
    pstartdate: "2022-01-05T20:00:00.000Z",
    penddate: "2022-01-11T20:00:00.000Z",
    tasks_count: "0",
    createdby: "25"
  }
]